name: Create Release

on:
  push:
    tags:
      - 'v*'  # 推送标签触发，如 v1.0.0
  workflow_dispatch:  # 添加手动触发支持
    inputs:
      version:
        description: '版本号 (例如: v1.0.0)'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Package files
        run: |
          zip -r iptv-api.zip . -x "*.git*"
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: iptv-api.zip
          name: Release ${{ github.event.inputs.version || github.ref_name }}
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
